final List<Map<String, dynamic>> productsData = [
  {
    "id": 2001,
    "title": "Paracetamol",
    "main": "Tablets - 5mg",
    "type": "capsule",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2002,
    "title": "kezitill susp",
    "type": "Axetil",
    "main": "Oral suspension - 125mg",
    "soldBy": "Pharmaceuticals ",
    "quantity": 1,
    "price": 250,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a Kezitill ",
  },
  {
    "id": 2003,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Em Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a garlic oil contains ...",
  },
  {
    "id": 2004,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2005,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2006,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2007,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2008,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
  {
    "id": 2009,
    "title": "Garlic Oil",
    "type": "Garlic Oil",
    "main": "Soft Gel",
    "soldBy": "Emzor Pharmaceuticals",
    "quantity": 1,
    "price": 150,
    "size": 20,
    "constituents": "tamol",
    "dispensed": "Packs",
    "imageUrl": "generico",
    "description": "A pack of a paracetamol contains 12 capsules",
  },
];
